name: .Net Analyzer
on: [push, pull_request]
jobs:
  lint:
    name: Run Analyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: .NET Lint
        uses: zyactions/dotnet-lint@v1
        with:
          workspace: 'AsBuiltReportChart.sln'
          implicit-restore: true